// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: pkg/proto/metrics_payload.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The data type of a Metric value. Deferred from OpenMetrics types.
type MetricsPayload_MetricType int32

const (
	MetricsPayload_UNKNOWN MetricsPayload_MetricType = 0 // Default value. Should not be used.
	MetricsPayload_GAUGE   MetricsPayload_MetricType = 1
	MetricsPayload_INFO    MetricsPayload_MetricType = 4
)

// Enum value maps for MetricsPayload_MetricType.
var (
	MetricsPayload_MetricType_name = map[int32]string{
		0: "UNKNOWN",
		1: "GAUGE",
		4: "INFO",
	}
	MetricsPayload_MetricType_value = map[string]int32{
		"UNKNOWN": 0,
		"GAUGE":   1,
		"INFO":    4,
	}
)

func (x MetricsPayload_MetricType) Enum() *MetricsPayload_MetricType {
	p := new(MetricsPayload_MetricType)
	*p = x
	return p
}

func (x MetricsPayload_MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricsPayload_MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_metrics_payload_proto_enumTypes[0].Descriptor()
}

func (MetricsPayload_MetricType) Type() protoreflect.EnumType {
	return &file_pkg_proto_metrics_payload_proto_enumTypes[0]
}

func (x MetricsPayload_MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricsPayload_MetricType.Descriptor instead.
func (MetricsPayload_MetricType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_metrics_payload_proto_rawDescGZIP(), []int{0, 0}
}

type MetricsPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metrics []*MetricsPayload_Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *MetricsPayload) Reset() {
	*x = MetricsPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_metrics_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsPayload) ProtoMessage() {}

func (x *MetricsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metrics_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsPayload.ProtoReflect.Descriptor instead.
func (*MetricsPayload) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metrics_payload_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsPayload) GetMetrics() []*MetricsPayload_Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricsPayload_Label struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MetricsPayload_Label) Reset() {
	*x = MetricsPayload_Label{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_metrics_payload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsPayload_Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsPayload_Label) ProtoMessage() {}

func (x *MetricsPayload_Label) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metrics_payload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsPayload_Label.ProtoReflect.Descriptor instead.
func (*MetricsPayload_Label) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metrics_payload_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MetricsPayload_Label) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetricsPayload_Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MetricsPayload_Metric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string                    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type   MetricsPayload_MetricType `protobuf:"varint,2,opt,name=type,proto3,enum=spectate.agent.MetricsPayload_MetricType" json:"type,omitempty"`
	Labels []*MetricsPayload_Label   `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	// Types that are assignable to Value:
	//
	//	*MetricsPayload_Metric_UnknownValue
	//	*MetricsPayload_Metric_GaugeValue
	//	*MetricsPayload_Metric_InfoValue
	Value     isMetricsPayload_Metric_Value `protobuf_oneof:"value"`
	Timestamp *timestamppb.Timestamp        `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *MetricsPayload_Metric) Reset() {
	*x = MetricsPayload_Metric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_metrics_payload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsPayload_Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsPayload_Metric) ProtoMessage() {}

func (x *MetricsPayload_Metric) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metrics_payload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsPayload_Metric.ProtoReflect.Descriptor instead.
func (*MetricsPayload_Metric) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metrics_payload_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MetricsPayload_Metric) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetricsPayload_Metric) GetType() MetricsPayload_MetricType {
	if x != nil {
		return x.Type
	}
	return MetricsPayload_UNKNOWN
}

func (x *MetricsPayload_Metric) GetLabels() []*MetricsPayload_Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (m *MetricsPayload_Metric) GetValue() isMetricsPayload_Metric_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *MetricsPayload_Metric) GetUnknownValue() *MetricsPayload_UnknownValue {
	if x, ok := x.GetValue().(*MetricsPayload_Metric_UnknownValue); ok {
		return x.UnknownValue
	}
	return nil
}

func (x *MetricsPayload_Metric) GetGaugeValue() *MetricsPayload_GaugeValue {
	if x, ok := x.GetValue().(*MetricsPayload_Metric_GaugeValue); ok {
		return x.GaugeValue
	}
	return nil
}

func (x *MetricsPayload_Metric) GetInfoValue() *MetricsPayload_InfoValue {
	if x, ok := x.GetValue().(*MetricsPayload_Metric_InfoValue); ok {
		return x.InfoValue
	}
	return nil
}

func (x *MetricsPayload_Metric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type isMetricsPayload_Metric_Value interface {
	isMetricsPayload_Metric_Value()
}

type MetricsPayload_Metric_UnknownValue struct {
	UnknownValue *MetricsPayload_UnknownValue `protobuf:"bytes,4,opt,name=unknown_value,json=unknownValue,proto3,oneof"`
}

type MetricsPayload_Metric_GaugeValue struct {
	GaugeValue *MetricsPayload_GaugeValue `protobuf:"bytes,5,opt,name=gauge_value,json=gaugeValue,proto3,oneof"`
}

type MetricsPayload_Metric_InfoValue struct {
	InfoValue *MetricsPayload_InfoValue `protobuf:"bytes,9,opt,name=info_value,json=infoValue,proto3,oneof"`
}

func (*MetricsPayload_Metric_UnknownValue) isMetricsPayload_Metric_Value() {}

func (*MetricsPayload_Metric_GaugeValue) isMetricsPayload_Metric_Value() {}

func (*MetricsPayload_Metric_InfoValue) isMetricsPayload_Metric_Value() {}

// Value for UNKNOWN Metric.
type MetricsPayload_UnknownValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required.
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MetricsPayload_UnknownValue) Reset() {
	*x = MetricsPayload_UnknownValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_metrics_payload_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsPayload_UnknownValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsPayload_UnknownValue) ProtoMessage() {}

func (x *MetricsPayload_UnknownValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metrics_payload_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsPayload_UnknownValue.ProtoReflect.Descriptor instead.
func (*MetricsPayload_UnknownValue) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metrics_payload_proto_rawDescGZIP(), []int{0, 2}
}

func (x *MetricsPayload_UnknownValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Value for GAUGE Metric.
type MetricsPayload_GaugeValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required.
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MetricsPayload_GaugeValue) Reset() {
	*x = MetricsPayload_GaugeValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_metrics_payload_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsPayload_GaugeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsPayload_GaugeValue) ProtoMessage() {}

func (x *MetricsPayload_GaugeValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metrics_payload_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsPayload_GaugeValue.ProtoReflect.Descriptor instead.
func (*MetricsPayload_GaugeValue) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metrics_payload_proto_rawDescGZIP(), []int{0, 3}
}

func (x *MetricsPayload_GaugeValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Value for INFO Metric.
type MetricsPayload_InfoValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional.
	Info []*MetricsPayload_Label `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
}

func (x *MetricsPayload_InfoValue) Reset() {
	*x = MetricsPayload_InfoValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_metrics_payload_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsPayload_InfoValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsPayload_InfoValue) ProtoMessage() {}

func (x *MetricsPayload_InfoValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metrics_payload_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsPayload_InfoValue.ProtoReflect.Descriptor instead.
func (*MetricsPayload_InfoValue) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metrics_payload_proto_rawDescGZIP(), []int{0, 4}
}

func (x *MetricsPayload_InfoValue) GetInfo() []*MetricsPayload_Label {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_pkg_proto_metrics_payload_proto protoreflect.FileDescriptor

var file_pkg_proto_metrics_payload_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x8d, 0x06, 0x0a, 0x0e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x3f, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x07, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x2f, 0x0a, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0xc7, 0x03, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x3d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x29, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x12, 0x52, 0x0a, 0x0d, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x67, 0x61, 0x75, 0x67, 0x65, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x47, 0x61, 0x75, 0x67, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x67, 0x61, 0x75, 0x67, 0x65, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x48, 0x00, 0x52, 0x09, 0x69, 0x6e, 0x66, 0x6f, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x1a, 0x24, 0x0a, 0x0c, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x22, 0x0a, 0x0a, 0x47, 0x61, 0x75, 0x67, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x45, 0x0a, 0x09, 0x49,
	0x6e, 0x66, 0x6f, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x22, 0x2e, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x47, 0x41, 0x55, 0x47, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f,
	0x10, 0x04, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_metrics_payload_proto_rawDescOnce sync.Once
	file_pkg_proto_metrics_payload_proto_rawDescData = file_pkg_proto_metrics_payload_proto_rawDesc
)

func file_pkg_proto_metrics_payload_proto_rawDescGZIP() []byte {
	file_pkg_proto_metrics_payload_proto_rawDescOnce.Do(func() {
		file_pkg_proto_metrics_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_metrics_payload_proto_rawDescData)
	})
	return file_pkg_proto_metrics_payload_proto_rawDescData
}

var file_pkg_proto_metrics_payload_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_metrics_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_proto_metrics_payload_proto_goTypes = []interface{}{
	(MetricsPayload_MetricType)(0),      // 0: spectate.agent.MetricsPayload.MetricType
	(*MetricsPayload)(nil),              // 1: spectate.agent.MetricsPayload
	(*MetricsPayload_Label)(nil),        // 2: spectate.agent.MetricsPayload.Label
	(*MetricsPayload_Metric)(nil),       // 3: spectate.agent.MetricsPayload.Metric
	(*MetricsPayload_UnknownValue)(nil), // 4: spectate.agent.MetricsPayload.UnknownValue
	(*MetricsPayload_GaugeValue)(nil),   // 5: spectate.agent.MetricsPayload.GaugeValue
	(*MetricsPayload_InfoValue)(nil),    // 6: spectate.agent.MetricsPayload.InfoValue
	(*timestamppb.Timestamp)(nil),       // 7: google.protobuf.Timestamp
}
var file_pkg_proto_metrics_payload_proto_depIdxs = []int32{
	3, // 0: spectate.agent.MetricsPayload.metrics:type_name -> spectate.agent.MetricsPayload.Metric
	0, // 1: spectate.agent.MetricsPayload.Metric.type:type_name -> spectate.agent.MetricsPayload.MetricType
	2, // 2: spectate.agent.MetricsPayload.Metric.labels:type_name -> spectate.agent.MetricsPayload.Label
	4, // 3: spectate.agent.MetricsPayload.Metric.unknown_value:type_name -> spectate.agent.MetricsPayload.UnknownValue
	5, // 4: spectate.agent.MetricsPayload.Metric.gauge_value:type_name -> spectate.agent.MetricsPayload.GaugeValue
	6, // 5: spectate.agent.MetricsPayload.Metric.info_value:type_name -> spectate.agent.MetricsPayload.InfoValue
	7, // 6: spectate.agent.MetricsPayload.Metric.timestamp:type_name -> google.protobuf.Timestamp
	2, // 7: spectate.agent.MetricsPayload.InfoValue.info:type_name -> spectate.agent.MetricsPayload.Label
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_proto_metrics_payload_proto_init() }
func file_pkg_proto_metrics_payload_proto_init() {
	if File_pkg_proto_metrics_payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_metrics_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_metrics_payload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsPayload_Label); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_metrics_payload_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsPayload_Metric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_metrics_payload_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsPayload_UnknownValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_metrics_payload_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsPayload_GaugeValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_metrics_payload_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsPayload_InfoValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_proto_metrics_payload_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*MetricsPayload_Metric_UnknownValue)(nil),
		(*MetricsPayload_Metric_GaugeValue)(nil),
		(*MetricsPayload_Metric_InfoValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_metrics_payload_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_metrics_payload_proto_goTypes,
		DependencyIndexes: file_pkg_proto_metrics_payload_proto_depIdxs,
		EnumInfos:         file_pkg_proto_metrics_payload_proto_enumTypes,
		MessageInfos:      file_pkg_proto_metrics_payload_proto_msgTypes,
	}.Build()
	File_pkg_proto_metrics_payload_proto = out.File
	file_pkg_proto_metrics_payload_proto_rawDesc = nil
	file_pkg_proto_metrics_payload_proto_goTypes = nil
	file_pkg_proto_metrics_payload_proto_depIdxs = nil
}
